### ISSUE TITLE
Errno 121 : Remote I/O error

### ISSUE THREAD

**Issue by jamesjohnson82** [geeekpi/upsplus#86]
I have been trying everything to get my RPi4B to communicate with the USP Plus but I continually get this error 

```
pi@ImpactRemote:~/upsplus $ python3 OTA_firmware_upgrade.py
Traceback (most recent call last):
  File "OTA_firmware_upgrade.py", line 23, in <module>
    aReceiveBuf.append(bus.read_byte_data(DEVICE_ADDR, i))
  File "/usr/local/lib/python3.7/dist-packages/smbus2/smbus2.py", line 433, in read_byte_data
    ioctl(self.fd, I2C_SMBUS, msg)
OSError: [Errno 121] Remote I/O error
pi@ImpactRemote:~/upsplus $ 

```

Remote I/O error.

I have been unable to find any information on what this error means and how to troubleshoot it.  as you can see below its stopping the install of the UPS Plus and failing 

```
pi@ImpactRemote:~/upsplus $ sudo ./install.sh
[info] Welcome to 52Pi Technology UPS Plus auto-install Program!.
[info] More information please visit here:.
[info] -----------------------------------------------------.
[info] https://wiki.52pi.com/index.php/UPS_Plus_SKU:_EP-0136.
[info] -----------------------------------------------------.
[info] Start the configuration environment check....
[ ok ] Network status is ok....
[info] Start the software check....
[ ok ] git has been installed..
[ ok ] pi-ina219 library has been installed.
[info] Installing smbus2 library....
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: smbus in /usr/local/lib/python3.7/dist-packages (1.1.post2)
Requirement already satisfied: smbus2 in /usr/local/lib/python3.7/dist-packages (0.4.1)
[ ok ] smbus2 Installation successful..
[info] create /root/bin directory....
[info] Create python3 script in location: /root/bin/upsPlus.py Successful.
[ ok ] Create UPS Plus IoT customer service python script successful.
[info] Add into general crontab list..
[info] crontab has been created successful!.
------------------------------------------------------------
------Current information of the detected Raspberry Pi------
------------------------------------------------------------
Raspberry Pi Supply Voltage: 5.152 V
Raspberry Pi Current Current Consumption: 7029.773 mA
Raspberry Pi Current Power Consumption: 36245.585 mW
------------------------------------------------------------
Traceback (most recent call last):
  File "/root/bin/upsPlus.py", line 38, in <module>
    ina_batt.configure()
  File "/usr/local/lib/python3.7/dist-packages/ina219.py", line 175, in configure
    self._max_expected_amps)
  File "/usr/local/lib/python3.7/dist-packages/ina219.py", line 310, in _calibrate
    self._calibration_register(calibration)
  File "/usr/local/lib/python3.7/dist-packages/ina219.py", line 356, in _calibration_register
    self.__write_register(self.__REG_CALIBRATION, register_value)
  File "/usr/local/lib/python3.7/dist-packages/ina219.py", line 388, in __write_register
    self._i2c.writeList(register, register_bytes)
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_GPIO/I2C.py", line 127, in writeList
    self._bus.write_i2c_block_data(self._address, register, data)
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_PureIO/smbus.py", line 368, in write_i2c_block_data
    self._device.write(data)
OSError: [Errno 121] Remote I/O error
[FAIL] UPS Plus Installation is Incomplete! ... failed!
[info] Please visit wiki for more information:.
[info] -----------------------------------------------------.
[info] https://wiki.52pi.com/index.php/UPS_Plus_SKU:_EP-0136.
[info] -----------------------------------------------------.
pi@ImpactRemote:~/upsplus $ 

```

Thanks for the assistance.

**Comment by vali103** [comment]
Hi, my problem was solved by upgrading the UPS firmware.

**Comment by mmaga** [comment]
> Hi, my problem was solved by upgrading the UPS firmware.

That is what @jamesjohnson82 is trying to do.
Which firmware version did you get? Mine is version 10 and I still receive Errno 121 : Remote I/O error randomly.

**Comment by ArjenR49** [comment]
I had the same issue and the discussion can be found at:
https://github.com/frtz13/UPSPlus_mqtt/issues/23

(The error message Gindse invoer-/uitvoerfout is dutch for Remote input/output error.)

**Comment by vali103** [comment]
> > Hi, my problem was solved by upgrading the UPS firmware.
> 
> That is what @jamesjohnson82 is trying to do. Which firmware version did you get? Mine is version 10 and I still receive Errno 121 : Remote I/O error randomly.

Now i have firmware v10 . But now other strange things started to happen: 
1. Randomly cut the power for raspberry, (no shut down sequence). And the same after 1 min if i unplug the power. https://github.com/geeekpi/upsplus/issues/71
2.  Randomly i got the error back ( Errno 121 : Remote I/O error) but is ok after 1 sec or so
3. I never see the battery fully charged.
pi@raspberrypi:~ $ i2cdetect -y 1  
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- 17 -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- 3c -- -- -- 
40: 40 -- -- -- -- 45 -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- UU -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --    

4. I don't know what UU means :)) it suposed to be 68

**Comment by hellresistor** [comment]
try run command with sudo ?

**Comment by hellresistor** [comment]
> The battery is never fully charged also, and the fourth led is always blinking, even when the UPS is off but connected to the power source.

Friend that was the fact .. battery will keep charge and discharge.. not exist a 'by-pass to Direct current cable'.. take it in consideration the 4th led blink  it just a information the power cable its connected!

**Comment by mmaga** [comment]
I had to set baud rate back to 115200 (best rate based on the OLED specs) or the unit would never be out of OTA Firmware Upgrade Mode (0x18). 
Maybe some of you knows which is the recommended baud rate for the UPS Plus.

**Comment by mmaga** [comment]
> > The battery is never fully charged also, and the fourth led is always blinking, even when the UPS is off but connected to the power source.
> 
> Friend that was the fact .. battery will keep charge and discharge.. not exist a 'by-pass to Direct current cable, after full batteries'.. take it in consideration the 4th led blink it just a information the power cable its connected!

... and it looks like there is no way to use it connected to the power cable without batteries also. Is it true?

**Comment by hellresistor** [comment]
> ... and it looks like there is no way to use it connected to the power cable without batteries also. Is it true?

what is a propose about UPS ?? ... :\

**Comment by mmaga** [comment]
> > ... and it looks like there is no way to use it connected to the power cable without batteries also. Is it true?
> 
> what is a propose about UPS ?? ... :\

Just in case you run out of batteries and have no one around.

**Comment by ntahal** [comment]
I had a similar problem where my ups device EP-0136 using the OTA firmware update.
All my values were still showing up correctly when using the "Full-featured-demo-code.py" and "upsplus.py". but upgrading gave me the same error as:
pi@device:~/upsplus $ python3 OTA_firmware_upgrade.py
Traceback (most recent call last):
  File "OTA_firmware_upgrade.py", line 23, in <module>
    aReceiveBuf.append(bus.read_byte_data(DEVICE_ADDR, i))
  File "/usr/local/lib/python3.7/dist-packages/smbus2/smbus2.py", line 433, in read_byte_data
    ioctl(self.fd, I2C_SMBUS, msg)
OSError: [Errno 121] Remote I/O error

I managed to upgrade the firmware by following the second way of upgrading using the EP-0136 wiki's Method 2.

**Comment by hellresistor** [comment]
have you run this` i2cset -y 1 0x17 50 127 b` and than shutdown rpi, REMOVE BATTERIES. and than put them again on ups... ?!?!?
